/**
 * Zod Schemas for AI Response Validation
 * Using structured output with generateObject for type safety
 */

import { z } from "zod";

// ============================================================================
// Task Breakdown Schemas
// ============================================================================

/**
 * Schema for a single subtask generated by AI
 */
export const subtaskSchema = z.object({
  title: z
    .string()
    .min(1)
    .max(100)
    .describe("Clear, actionable title for the subtask"),
  description: z
    .string()
    .max(500)
    .optional()
    .describe("Brief description of what this subtask involves"),
  estimatedDurationMinutes: z
    .number()
    .int()
    .min(5)
    .max(240)
    .describe("Estimated time in minutes (5-240)"),
  order: z
    .number()
    .int()
    .min(1)
    .describe("Suggested completion order"),
});

/**
 * Schema for task breakdown response
 */
export const taskBreakdownSchema = z.object({
  subtasks: z
    .array(subtaskSchema)
    .min(2)
    .max(10)
    .describe("List of 2-10 subtasks that break down the parent task"),
  reasoning: z
    .string()
    .max(200)
    .optional()
    .describe("Brief explanation of the breakdown strategy"),
  totalEstimatedMinutes: z
    .number()
    .int()
    .describe("Sum of all subtask durations"),
});

export type Subtask = z.infer<typeof subtaskSchema>;
export type TaskBreakdown = z.infer<typeof taskBreakdownSchema>;

// ============================================================================
// Copilot Chat Schemas
// ============================================================================

/**
 * Schema for copilot tool calls
 */
export const findTimeSlotResultSchema = z.object({
  slots: z.array(z.object({
    date: z.string().describe("ISO date string"),
    startTime: z.string().describe("HH:MM format"),
    endTime: z.string().describe("HH:MM format"),
    available: z.boolean(),
  })),
  recommendation: z.string().optional(),
});

export const rescheduleResultSchema = z.object({
  taskId: z.string(),
  oldStart: z.string().optional(),
  newStart: z.string(),
  newEnd: z.string(),
  success: z.boolean(),
  message: z.string(),
});

export const taskSummarySchema = z.object({
  totalTasks: z.number(),
  byState: z.record(z.string(), z.number()),
  byPriority: z.record(z.string(), z.number()),
  overdueTasks: z.number(),
  scheduledTasks: z.number(),
  upcomingDeadlines: z.array(z.object({
    taskId: z.string(),
    title: z.string(),
    deadline: z.string(),
    daysRemaining: z.number(),
  })),
});

export type FindTimeSlotResult = z.infer<typeof findTimeSlotResultSchema>;
export type RescheduleResult = z.infer<typeof rescheduleResultSchema>;
export type TaskSummary = z.infer<typeof taskSummarySchema>;

// ============================================================================
// Categorization Schema
// ============================================================================

/**
 * Schema for AI task categorization (suggest workflow state)
 */
export const categorizationSchema = z.object({
  suggestedState: z.string().describe("Suggested workflow state name"),
  confidence: z.number().min(0).max(1).describe("Confidence score 0-1"),
  reasoning: z.string().max(100).optional(),
});

export type Categorization = z.infer<typeof categorizationSchema>;

// ============================================================================
// Chat Message Schema
// ============================================================================

/**
 * Schema for copilot response
 */
export const copilotResponseSchema = z.object({
  message: z.string().describe("The response message to the user"),
  action: z.enum([
    "none",
    "find_time",
    "reschedule",
    "create_task",
    "update_task",
    "summarize",
    "breakdown",
  ]).optional(),
  actionData: z.record(z.unknown()).optional(),
});

export type CopilotResponse = z.infer<typeof copilotResponseSchema>;
