-- Add subtask support to tasks table
-- Adds parent_task_id for hierarchical tasks and ai_generated flag

-- Add parent_task_id column for subtasks
ALTER TABLE tasks
ADD COLUMN parent_task_id UUID REFERENCES tasks(id) ON DELETE CASCADE;

-- Add ai_generated flag to track AI-generated subtasks
ALTER TABLE tasks
ADD COLUMN ai_generated BOOLEAN NOT NULL DEFAULT false;

-- Add depends_on_task_id for task dependencies (future use)
ALTER TABLE tasks
ADD COLUMN depends_on_task_id UUID REFERENCES tasks(id) ON DELETE SET NULL;

-- Create index for parent task lookups
CREATE INDEX idx_tasks_parent_task_id ON tasks(parent_task_id) WHERE parent_task_id IS NOT NULL;

-- Create index for dependency lookups
CREATE INDEX idx_tasks_depends_on_task_id ON tasks(depends_on_task_id) WHERE depends_on_task_id IS NOT NULL;

-- Comment on columns
COMMENT ON COLUMN tasks.parent_task_id IS 'Reference to parent task for subtasks';
COMMENT ON COLUMN tasks.ai_generated IS 'Whether this task was generated by AI breakdown';
COMMENT ON COLUMN tasks.depends_on_task_id IS 'Task that must be completed before this task';
